[project]
name = "lightning-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lightning>=2.5.2",
    "torch>=2.7.1",
]
